# Thanks <3

debug:
  enabled: true
  permission: hub.debug
messages:
  success-message: <#69d9ff>You are now in the <i>Hub</i>.
  already-connected-message: <#ff614d>You are already on the <i>Hub</i>.
  connection-in-progress-message: <#ff9c59>In Progress...
  server-disconnected-message: <#ff614d>The Lobby Server is Offline...
  connection-cancelled-message: <#ff614d>Transfer cancelled.
system-messages:
  players-only-command-message: <#ff9c59>This Command is only available to Players.
  no-lobby-found-message: <#ff9c59>I'm sorry! i was unable to find a Lobby Server
    for you.
kick-message:
  enabled: true
  prefix: <red>
  suffix: ''
base-hub-command: hub
aliases:
- lobby
- leave
hide-hub-command-on-lobby: ^(?!.*).$
auto-select:
  on-join: true
  on-server-kick: true
last-lobby:
  enabled: true
lobby-groups:
- name: main
  lobbies:
  - lobby
  - teamlobby
  - premiumlobby
- name: minigame
  lobbies:
  - ffa-lobby
lobbies:
- name: teamlobby
  filter: (?i)^teamlobby.*
  permission: hub.team
  priority: 2
  parent: ''
  parent-groups:
  - lobby
  commands:
    teamlobby:
      standalone: false
      subcommand: true
      hide-on: ^(?!.*).$
  autojoin: false
  overwrite-messages: {}
- name: premiumlobby
  filter: (?i)^premiumlobby.*
  permission: hub.premium
  priority: 1
  parent: ''
  parent-groups:
  - lobby
  commands:
    premiumlobby:
      standalone: true
      subcommand: false
      hide-on: ^(?!.*).$
  autojoin: true
  overwrite-messages:
    success-message: <#69d9ff>You are now in the <b>Premium Hub</b>.
- name: ffa-lobby
  filter: (?i)^lobby-minestom.*
  permission: ''
  priority: 0
  parent: ''
  parent-groups:
  - main
  commands:
    ffa:
      standalone: false
      subcommand: true
      hide-on: ^(?!.*).$
  autojoin: true
  overwrite-messages: {}
- name: lobby
  filter: (?i)^lobby.*
  permission: ''
  priority: 0
  parent: ''
  parent-groups: []
  commands:
    base:
      standalone: false
      subcommand: true
      hide-on: ^(?!.*).$
  autojoin: true
  overwrite-messages: {}
placeholder:
  server:
    example: lobby-1
    key: server
    enabled: true
  server-host:
    example: 127.0.0.1
    key: server-host
    enabled: false
  server-port:
    example: '25565'
    key: server-port
    enabled: false
  server-player-count:
    example: '0'
    key: server-player-count
    enabled: true
  server-player-per-player-username:
    example: apitoken
    key: server-player-%i-username
    enabled: false
    placeholder: '%i'
  server-player-per-player-uuid:
    example: f9de374c-cb78-4c5c-aa2f-4a53ae981f9d
    key: server-player-%i-uuid
    enabled: false
    placeholder: '%i'
  lobby:
    example: lobby
    key: lobby
    enabled: true
  lobby-filter:
    example: (?i)^lobby.*
    key: lobby-filter
    enabled: false
  lobby-require-permission:
    example: 'true'
    key: lobby-require-permission
    enabled: false
  lobby-permission:
    example: hub.user
    key: lobby-permission
    enabled: true
  lobby-priority:
    example: '0'
    key: lobby-priority
    enabled: false
  lobby-command-per-command-standalone:
    example: 'true'
    key: lobby-command-%s-standalone
    enabled: false
  lobby-command-per-command-subcommand:
    example: 'true'
    key: lobby-command-%s-subcommand
    enabled: false
  lobby-command-per-command-hide-on:
    example: ^(?!.*).$
    key: lobby-command-%s-hide-on
    enabled: false
  lobby-autojoin:
    example: 'true'
    key: lobby-autojoin
    enabled: false
  player:
    example: Freddiio
    key: player
    enabled: true
  player-uuid:
    example: c5eb5df7-b7a9-4919-a9bc-7f59c8bee980
    key: player-uuid
    enabled: false
finder:
  start-duration: 20
  increment-duration: 20
  max-duration: 200
  refresh-interval-in-ticks: 40
update-checker:
  enabled: true
  notification: ''
  check-interval-in-min: 30
