version: 1
generated-at: '2025-12-23T17:27:10.896668378Z'
servers:
- lobby
- lobby-neoforge
- lobby-fabric
- lobby-minestom
- ffa
- paper
- fabric
- minestom
- neoforge
lobbies:
- teamlobby
- premiumlobby
- ffa-lobby
- lobby
users: []
