version: 1
generated-at: '2026-01-07T04:02:05.981208550Z'
servers:
- ffa
- lobby
- lobby-neoforge
- lobby-fabric
- lobby-minigames
- lobby-minestom
- paper
- fabric
- minestom
- neoforge
lobbies:
- teamlobby
- premiumlobby
- minigames-lobby
- ffa-lobby
- lobby
- ffa
users: []
