[versions]
fabric-loom = "1.13.3"
neoforge-moddev = "2.0.134"
configurate = "4.1.2"

[plugins]
fabric-loom = { id = "fabric-loom", version.ref = "fabric-loom" }
neoforge-moddev = { id = "net.neoforged.moddev", version.ref = "neoforge-moddev" }

[libraries]
configurate-core = { group = "org.spongepowered", name = "configurate-core", version.ref = "configurate" }
configurate-yaml = { group = "org.spongepowered", name = "configurate-yaml", version.ref = "configurate" }
